"""Regenerate the bundled ECDSA.Fail manifest snapshot.

Copies the small `manifest.json` (metrics/benchmark/verification data
only -- never the .kmx artifacts) from the external, frozen ECDSA.Fail
dataset root into data/ecdsa/manifest_snapshot.json inside this repo, so
the ECDSA.Fail demo section can run in environments without access to
that external root (e.g. a Streamlit Community Cloud deployment).

This script only ever READS the external dataset -- it never writes to
it, and it never touches the .kmx artifacts.

Run from the project root:

    python scripts/snapshot_ecdsa_manifest.py

Uses QCH_ECDSA_DATASET_ROOT if set, otherwise the default local dataset
path (see src/ecdsa_config.py).
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from ecdsa_config import SNAPSHOT_PATH, external_manifest_path  # noqa: E402


def main() -> None:
    source_path = external_manifest_path()
    if not source_path.exists():
        print(f"External manifest not found: {source_path}")
        print("Set QCH_ECDSA_DATASET_ROOT or check src/ecdsa_config.py's default.")
        sys.exit(1)

    manifest = json.loads(source_path.read_text(encoding="utf-8-sig"))

    # A note identifying this as a derived copy, not the authoritative
    # source -- ignored by src/ecdsa_adapter.py, which only reads the
    # original manifest.json fields.
    manifest["_demo_snapshot_notice"] = (
        f"Derived, lightweight copy of manifest.json from {source_path}, "
        f"generated by scripts/snapshot_ecdsa_manifest.py on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')} for portable/offline "
        "demo use (e.g. Streamlit Community Cloud, which has no access to the "
        "external dataset root). The frozen dataset at the path above remains "
        "the authoritative source; this snapshot is used only as a fallback."
    )

    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT_PATH.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"Wrote snapshot: {SNAPSHOT_PATH}")


if __name__ == "__main__":
    main()
